language: java

sudo: false

jobs:
  include:
    - stage: Event listeners
      before_script: cd event-listeners
    - stage: logging 1
      before script: cd logging1

notifications:
  email:
    on_success: change
    on_failure: always
