
sudo: false

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    -  env: JDK=adoptopenjdk11 + OpenJ9
       script: source ./install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
    # Java 11 "Oracle JDK"
    # - env: JDK='Oracle JDK 11'
    #  install: . ./install-jdk.sh -F 11 -L BCL

jobs:
  include:
    - stage: Event listeners
      language: java
      before_script: cd event-listeners
    - stage: logging 1
      language: java
      before script: cd logging1

notifications:
  email:
    on_success: change
    on_failure: always
