language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk8
  - openjdk9
  - openjdk10
sudo: false
script: mvn clean verify
notifications:
  email:
    on_success: change
    on_failure: always
