language: java

sudo: false

jobs:
  include:
    - stage: Event listeners
      before_script: cd event-listereners
      script: mvn clean verify
      jdk:
        - oraclejdk8
    - stage: logging 1
      before script: cd logging1
      script: mvn clean verify
      jdk:
        - oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: always
