language: java

sudo: false

jobs:
  include:
    - stage: Event listeners
      before_script: cd event-listeners
      script: mvn clean verify
    - stage: logging 1
      before script: cd logging1
      script: mvn clean verify

notifications:
  email:
    on_success: change
    on_failure: always
